"""empty message

Revision ID: 712dfac8df8c
Revises: 
Create Date: 2024-05-22 10:31:22.610085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '712dfac8df8c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('age', sa.String(), nullable=True),
    sa.Column('email_address', sa.String(), nullable=True),
    sa.Column('_hashed_password', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('carts_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cart_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cart_user_id'], ['users_table.id'], name=op.f('fk_carts_table_cart_user_id_users_table')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('items_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('item_user_id', sa.Integer(), nullable=True),
    sa.Column('item_cart_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_cart_id'], ['carts_table.id'], name=op.f('fk_items_table_item_cart_id_carts_table')),
    sa.ForeignKeyConstraint(['item_user_id'], ['users_table.id'], name=op.f('fk_items_table_item_user_id_users_table')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('items_table')
    op.drop_table('carts_table')
    op.drop_table('users_table')
    # ### end Alembic commands ###
