"""empty message

Revision ID: fe8e68867147
Revises: 712dfac8df8c
Create Date: 2024-05-23 12:34:54.471635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe8e68867147'
down_revision = '712dfac8df8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('img_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items_table', schema=None) as batch_op:
        batch_op.drop_column('img_url')
        batch_op.drop_column('price')

    # ### end Alembic commands ###
